### ISSUE TITLE
Clarification on Kendall's Tau Variant Used in Table 1 and Others

### ISSUE THREAD

**Issue by Silviase** [DavidMChan/clair#1]
Hello,

I've been examining the results presented in your paper, particularly `Table 1: Sample-level correlation (Kendall’s τ) with human judgments`. Your work's alignment with human evaluations is quite impressive. I'm curious about the specific variant of Kendall's tau that was used in this analysis. Was it tau-b, considering the potential for ties in the CLAIR method? I noticed tau-c is often used in other studies for such evaluations. Could you clarify which one was applied here?

(If you used default configuration of `scipy.stats.kendalltau`, it is tau-b)

Thank you for your insights and contributions to the field.

**Comment by DavidMChan** [comment]
Hello, thanks for taking a look at the work. In order to be consistent with the numbers drawn from the other works, we use tau-c, following the detailed discussion on evaluation methods in https://arxiv.org/pdf/2104.08718.pdf (Appendix A). Our system-level correlations leverage different models, as the model results from that paper are no longer available online, but in general, we did our best to follow their evaluation methods.
