### ISSUE TITLE
Reproduce CLAIR (GPT-3.5) Results on Flickr8K

### ISSUE THREAD

**Issue by YuigaWada** [DavidMChan/clair#2]
Hi,
I've been trying to reproduce the CLAIR (gpt-3.5) results for Flickr8K using this repo's code but encountered a discrepancy. My results show a score of 0.446, compared to the 0.616 reported in your paper. (The average of the three experiments was 0.462; a similar result was obtained when implemented from scratch instead of grazier).

Given the paper mentions "we found the variance to be relatively insignificant," I suspect my approach might be the issue but I cannot detect the problem. I've used kendall-C for metrics, consistent with the paper, and evaluated it with [PAC-S code](https://github.com/aimagelab/pacscore), so the metrics and evaluation code seem correct. I've also checked the prompts from `logging` and they seem accurate.

As I suspect my approach might be at fault, could you kindly provide the evaluation code or the output files of CLAIR that match the kendall scores reported in the paper? This would greatly assist in identifying where my reproduction differs. 

I’ve uploaded the clair output file where kendall is 0.445. Also uploaded the log file. [[here]](https://drive.google.com/drive/folders/15Qe2LOT3D-EZxzlUqQpQW6YJaPj4lMj2?usp=drive_link)

```python
import json
import scipy

with open("output.json") as f:
    data = json.load(f)

scores = {}
metrics = ["BLEU-4", "METEOR", "ROUGE", "CIDEr", "PAC-S", "RefPAC-S", "CLAIR", "human"]
for d in data:
    for metric in metrics:
        scores.setdefault(metric,[]).append(d[metric])

for k,v in scores.items():
    if k == "human": continue
    human_scores = scores["human"]
    kendalltau_b = 100 * scipy.stats.kendalltau(v, human_scores, variant='b')[0]
    kendalltau_c = 100 * scipy.stats.kendalltau(v, human_scores, variant='c')[0]
    print('%s \t Kendall Tau-b: %.3f \t  Kendall Tau-c: %.3f' % (k, kendalltau_b, kendalltau_c))

```

```bash
BLEU-4 	 Kendall Tau-b: 30.599 	  Kendall Tau-c: 30.776
METEOR 	 Kendall Tau-b: 41.538 	  Kendall Tau-c: 41.822
ROUGE 	 Kendall Tau-b: 32.139 	  Kendall Tau-c: 32.314
CIDEr 	 Kendall Tau-b: 43.602 	  Kendall Tau-c: 43.891
PAC-S 	 Kendall Tau-b: 53.920 	  Kendall Tau-c: 54.292
RefPAC-S 	 Kendall Tau-b: 55.480 	  Kendall Tau-c: 55.863
CLAIR 	 Kendall Tau-b: 54.327 	  Kendall Tau-c: 44.648
```

**Comment by DavidMChan** [comment]
Hello, thanks for bringing this to my attention! I ran your results against our evaluation code, and I found that, worryingly, our evaluation code generated the Tau-b numbers instead of the Tau-c numbers. We used a third-party evaluation script, and while they claim to have followed the evaluation protocol in [this work](https://arxiv.org/pdf/2104.08718.pdf), they used the default argument for the scipy learn version of Kendall's Tau, meaning that Tau-b numbers were computed instead of Tau-c numbers. 

I re-ran the evaluation using your code above, and found the following results on Flickr-8k:
```
CLAIR+GPT      Kendall Tau-b: 61.597    Kendall Tau-c: 51.399
CLAIR+PALM      Kendall Tau-b: 54.584    Kendall Tau-c: 30.664
CLAIR+CLAUDE      Kendall Tau-b: 56.263    Kendall Tau-c: 35.146
```
It seems that while the Tau-b is high, because of the ties that CLAIR generates, the Tau-c is significantly lower (as alluded to by #1).  While this accounts for some of the variance, a Tau-c of 51.399 is still significantly higher than the observed Tau-c of 44.68 that you're getting in your experiments. I've attached our experimental files, as well as the code originally used to generate the CLAIR results so you can check them against your implementation. Originally, I thought that the issue was caused by an increase in CLAIR failures (as we've seen some issues with CLAUDE-2, and the CLAIR prompt), but it doesn't seem from the log file that you're running into failures (there's no failed parsing in the entire file). Instead, it seems like this may be due to overall model degradation since we ran the original experiments in the CLAIR paper.

[flickr8k-palm-annotations.json](https://github.com/DavidMChan/clair/files/13868196/flickr8k-palm-annotations.json)
[flickr8k-gpt-annotations.json](https://github.com/DavidMChan/clair/files/13868197/flickr8k-gpt-annotations.json)
[flickr8k-claude-annotations.json](https://github.com/DavidMChan/clair/files/13868198/flickr8k-claude-annotations.json)

(Python files, could only upload .txt to github)
[clair_old.py.txt](https://github.com/DavidMChan/clair/files/13868301/clair_old.py.txt)
[llms.py.txt](https://github.com/DavidMChan/clair/files/13868302/llms.py.txt)

I double checked all of the tables in the paper, and the Tau results, while incorrect (they use tau-b instead of tau-c), are consistent. This means that with the exception some lines in Table 1 where results were copied across from existing papers, the numbers are generally still comparable (as we computed all of the other numbers in the paper with the same evaluation toolkit). We are currently working to update the paper on ArXiV to clarify that the results use tau-b, update the numbers in Table 1, and update the main README.md file to make this clear. I apologize for this - I should have been more diligent when double checking the correctness of our evaluation libraries. 

See Revision: https://github.com/acl-org/acl-anthology/issues/3017

**Comment by YuigaWada** [comment]
I now understand that the CLAIR evaluation mistakenly utilized Kendall's Tau-b instead of Tau-c. 

I appreciate your efforts to update the paper and provide this clarification. Your prompt response and dedication to maintaining accuracy in your research are greatly appreciated!
